name: Deploy para Produção

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Baixar JAR da release homolog-latest
      uses: dsaltares/fetch-gh-release-asset@v1
      with:
        repo: ${{ github.repository }}
        version: tags/homolog-latest
        file: tarefa-0.0.1-SNAPSHOT.jar
        token: ${{ secrets.GH_PAT }}

    - name: 🚚 Enviar JAR para a VM (Produção)
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "tarefa-0.0.1-SNAPSHOT.jar"
        target: "/home/${{ secrets.VM_USER }}/prod"

    - name: 🐳 Reiniciar container app-prod com novo JAR (com senha)
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker exec app-prod pkill -f 'java -jar' || true
          docker exec -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} -d app-prod java -jar /app/tarefa-0.0.1-SNAPSHOT.jar
